language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '6'
before_script:
  - npm prune
  - npm i cypress@0.20.1
script:
  - npm test
  - $(npm bin)/cypress run
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
